[package]
name = "workspacer"
version = "0.1.0"
authors = ["ustulation <ustulation@gmail.com>"]

[workspace]
members = ["safe_core", "safe_authenticator", "safe_app"]

[lib]
crate_type = ["rlib", "staticlib"]
